### ISSUE TITLE
tested against sphinx v4?

### ISSUE THREAD

**Issue by chrisjsewell** [sunpy/ablog#101]
Heya, note sphinx v4 will be released very soon and you don't pin your sphinx requirement in setup.cfg (e.g. `sphinx>=2,<4`), so it might be good to test it against this if you haven't already 😄 (there are sphinx v4 beta releases available on PyPI)

**Comment by nabobalis** [comment]
In theory we test with sphinx master but looking at the actual build, it seems to be the wrong version.

**Comment by chrisjsewell** [comment]
thanks for the quick reply!
maybe it would be good to add your tests as a github workflow as well 😬

**Comment by nabobalis** [comment]
It is a bit opaque but I really like using azure pipelines.

**Comment by chrisjsewell** [comment]
oh yeh, I didn't notice the config file for that. Well whatever floats your boat 😉 
maybe add a link to the pipeline and its latest results in the README?

**Comment by chrisjsewell** [comment]
Cheers

**Comment by nabobalis** [comment]
Turns out we did not in fact test it properly as myst-parser had sphinx <4. I have worked around this in our tox file.

**Comment by chrisjsewell** [comment]
well thats my fault; too busy telling everyone else to upgrade to sphinx 4 lol.
(thats a least one thing that requires a change there, so gradually getting round to it, but anyhow thats the point of pinning it to <4 until its good to go)

**Comment by nabobalis** [comment]
Our test suite seems to be ok with it.
