### ISSUE TITLE
Updating the `index.html` template

### ISSUE THREAD

**Issue by errbufferoverfl** [sunpy/ablog#111]
### Description

Hi folks, I am looking for more information on how the `postlist` used in the `index.html` page is generated -- I've had a look through all of the existing templates and source code and I'm unable to find where I can inject additional HTML / Jinja to change the current layout, as I'd like it to take on a look similar to the archive.

I've had great success in changing the pages for archive, category, tags etc. but as far as I can tell, the index is passed straight to `page.html` with no intermediate steps.

Could you please point me in the right direction?

**Comment by nabobalis** [comment]
Hi @errbufferoverfl, sorry for never responding. 

I don't really know how the system works, so I am unable to help.
I suspect it's something deeper in sphinx than in `ablog` but I am very unsure on this.

**Comment by errbufferoverfl** [comment]
No worries @nabobalis 😄 
I'll take a deeper look into Sphinx and see if I can find anything, if I do I'll be sure to post an update!
