### ISSUE TITLE
Markdown Front Matter 'tags' WARNING in HTML Target Build

### ISSUE THREAD

**Issue by gloc-mike** [sunpy/ablog#128]
### Describe the bug

I have been testing Ablog with Sphinx (and MyST extension) and when I create a post using front matter and then build to the HTML target the following warning appears:
`WARNING:root:fail to eval tags: test1, test2`

The post looks like this:
```
---
blogpost: true
date: Oct 10, 2020
author: Me
tags: test1, test2
location: World
category: Manual
language: English
---

# Another Test Post
```

I can see the warning text i.e., fail to eval, in the Ablog class called `CheckFrontMatter`:

```
# Pull the metadata for the page to check if it is a blog post
metadata = {fn.children[0].astext(): fn.children[1].astext() for fn in docinfo.traverse(nodes.field)}
tags = metadata.get("tags")
if isinstance(tags, str):
    # myst_parser store front-matter field to TextNode in dict_to_fm_field_list.
    # like ["a", "b", "c"]
    # remove [] and quote
    try:
         tags = eval(tags)
         metadata["tags"] = ",".join(tags)
     except Exception:
          logging.warning(f"fail to eval tags: {tags}")
```

### To Reproduce

Create a new post but use front matter and include `tags`.

### What happened?

A warning is raised

### Expected behavior

I expected `tags` to be acceptable front matter.

having said that, the example front matter on the [markdown Ablog support page](https://ablog.readthedocs.io/en/latest/manual/markdown/), does not include `tags`. :)

### Screenshots

![Screen Shot 2022-03-06 at 6 37 23 pm](https://user-images.githubusercontent.com/2324626/156913845-b9dcd784-bb52-4868-9eb2-de97a1cc0576.png)

### System Details

Python 3.9.8
Sphinx 4.4.0
Ablog 0.10.23
Myst-parser 0.17.0

### Installation method

pip

**Comment by nabobalis** [comment]
Hi everyone, 

This should now be fixed in the latest version of ablog!
