### ISSUE TITLE
Wrong post URL in atom.xml when we have multiple blog languages

### ISSUE THREAD

**Issue by SilverRainZ** [sunpy/ablog#136]
### Describe the bug

All my posts directly located under path [`blog`](https://github.com/SilverRainZ/bullet/tree/master/blog), but in the generated atom.xml, all post URL has a extra "zh_CN" insuffix:

```xml
<feed xml:lang="zh_CN">
<id>https://silverrainz.me/</id>
<title>银色子弹</title>
<updated>2022-04-22T12:17:50.750363+00:00</updated>
<link href="https://silverrainz.me/"/>
<link href="https://silverrainz.me/zh_CN/blog/atom.xml" rel="self"/>
<generator uri="https://ablog.readthedocs.org/" version="0.10.25">ABlog</generator>
<subtitle>Yes silver bullet here.</subtitle>
<entry>
<id>
https://silverrainz.me/zh_CN/blog/idf-reverse-writeup.html   <<<<<<<<<<<<<<<<<<<<<<< SEE EHRE
</id>
<title>IDF 实验室逆向题部分题解</title>
<updated>2015-01-02T00:00:00+00:00</updated>
<author>
<name>Shengyu Zhang</name>
</author>
....
```

The correct URL should be https://silverrainz.me/blog/idf-reverse-writeup.html

The full atom.xml file: https://gist.github.com/SilverRainZ/88a706344449d8f7f9fd587ac52e1e94

### To Reproduce

Have multiple entries in your `blog_languages` confval, for example:

I have the following snippet in my `conf.py`:

```py
blog_path = 'blog'
# ...
blog_languages = {
    'zh_CN': ('Chinese', None),
    'en':     ('English',  None),
}
blog_default_language = 'zh_CN'
```

If I changes the conf to:

```py
blog_path = 'blog'
# ...
blog_languages = {
    'zh_CN': ('Chinese', None),
    # 'en':     ('English',  None),
}
blog_default_language = 'zh_CN'
```

Everything goes well.

### System Details

- python 3.10.4
- sphinx 4.5.0
- ablog 0.10.25

**Comment by nabobalis** [comment]
I thought I would try to fix this in https://github.com/sunpy/ablog/pull/142 
Changing to make sure that `join()` never gets a `Non`e value was simple enough but as far as I can see, the url should never have the language set in the URL. So I removed that block of code instead.

It should be in the next release of ablog.
