### ISSUE TITLE
Exception: raise TypeError(f'{funcname}() argument must be str, bytes, or ; due to mistake in ABLog config handling with multiple langua

### ISSUE THREAD

**Issue by AlbertMietus** [sunpy/ablog#137]
When Sphinx/ABlog is configured with multiple languages, like
```
blog_languages = {
    'nl'  : ('Nederlands', None),
    'en'  : ('English', None)
}
```

`post.generate_atom_feeds()` on line 684 goes (or can go) **wrong**
```
if len(blog.blog_languages) > 1:
        base_url = os_path_join(url, app.config.language)
```
When that unrelated _[app.config]_ `language` setting is not set (default), it's None. Which is a **not allowed** parameter in os-join-path (in generi Path; that is ultimately called).

### To Reproduce

Create a setting with 2 (or more) blog_languages, as shown above.  The related setting ``blog_default_language`` is a relevant. And enable atom-feed (default)

Then it goes wrong.

Remove that setting, or when it dict has length=1. It work

### Fix (suggestions)

* Check the value of `app.config.language`; when none, do not use
* Use the value of `blog_default_language` (when not none)
* When no default is available, use the first key (or any) of the `blog.blog_languages` dict.

> note: When that dict  has no entries, the issue does not arise

**Comment by SilverRainZ** [comment]
May be related to https://github.com/sunpy/ablog/issues/136.

**Comment by nabobalis** [comment]
I have added this commit: [`b17ce59` (#142)](https://github.com/sunpy/ablog/pull/142/commits/b17ce595040f604831a31b355df5910f32e9d64c) that I think will fix this problem.

It should be in the next release of ablog.
