### ISSUE TITLE
functionality search does not work

### ISSUE THREAD

**Issue by fraoustin** [sunpy/ablog#14]
Hi

I use ablog 0.9 with sphinx 1.7.1 and i have a problem
I generated a blog

```
ablog start
ablog build

```
And after on load a search with url http://127.0.0.1/search/index.html?q=first
and when i click on result i have a 404 error ... the url file:///C:/Users/faoustin/Downloads/ablog/_website/search/first-post/?highlight=first does not exist 

Can you help me, please

ps: with ablog 0.8 it's ok

**Comment by nabobalis** [comment]
Ah yes, I see. The search is not dropping the `/search/` in the url.

It does work in a live environment, so it seems to only be a bug in the serve/local build.  

I will see if I can trace to what change in 0.9 broke that local search and I will try to fix this and update the package as soon as I can.

**Comment by ericrmc** [comment]
Hi, I'm still having this issue too, even when deployed onto GitHub Pages.  I'm using Python 3.6.5 and ablog 0.9.2. A start/build still fails locally but I've not tested it on GitHub.

Has anyone found a workaround?

**Comment by nabobalis** [comment]
So I can't get this to happen if i `ablog serve` the built local website. Search seems to work at least for the docs in the repo. 

If i open the index.html directly, the search box goes to the wrong link.

**Comment by ericrmc** [comment]
That's ok, thanks for investigating again. Might be something to do with my environment. Happy to have this closed if others are.

**Comment by nabobalis** [comment]
I don't want to close this if its still there. It seems to have fixed itself with newer versions of Sphinx but I want people to check if they can.

**Comment by rayalan** [comment]
I think this matches https://github.com/sphinx-doc/sphinx/issues/4915, which has indeed been fixed.
