### ISSUE TITLE
any plans to support more themes?

### ISSUE THREAD

**Issue by huaiweicheng** [sunpy/ablog#16]

**Comment by nabobalis** [comment]
Any themes you had in mind? We (SunPy) use our own custom theme and it works with ablog for our website.

**Comment by huaiweicheng** [comment]
I find that ablog website is based on Alabaster. I am wondering whether ablog could support other popular themes such as sphinx_rtd_theme and so on since Alabaster is not suitable for mobile devices as good as rtd theme.

**Comment by nabobalis** [comment]
We use that a version of the `sphinx_rtd_theme` ourselves. It should work if you set the `html_theme` in your `conf.py`

**Comment by huaiweicheng** [comment]
I have tried a sphinx_rtd_theme based ablog project. I just change the Alabaster in conf.py into rtd.
It builds sucessfully. However, It turns out that the siderbar does not work correctly. It seems out the tags, archieves and Categories do not show as I expected. Do you do some CSS corrections of sphinx_rtd_theme locally?
![image](https://user-images.githubusercontent.com/4011117/38764020-b2cfa3ea-3fd9-11e8-9c3f-2e8f1debb364.png)

**Comment by nabobalis** [comment]
Yeah so the RTD theme pull in any generated API links. Which are what all those under Post are. 

Theoretically, if you delete the `docs/manual` folder and remake it, they should go.

**Comment by huaiweicheng** [comment]
Sure. I understand what you are meaning. I will check the codes and makes it accommodates with rtd theme which could generate the tags, archives and so on on the sidebar and ignore the API links later.
