### ISSUE TITLE
ablog and bibtex reflow issue

### ISSUE THREAD

**Issue by warmstarter** [sunpy/ablog#164]
### Describe the bug

When using ablog and bibtex together, it mostly renders ok, but the layout gets oddly varied by the size of the browser on a desktop/laptop when reflowing.

### To Reproduce

You can see this on my blog:
https://tryst.eris.yoga/

On the left bar you will see 'About' 'Bibliography' and 'TdM Dictionary'
'About' and 'TdM Dictionary' behave properly, 'Bibliograhy' does not.

To see, click on these and then change the size of the browser.
'About' and 'TdM Dictionary' will reflow (I think that is the term) properly.
'Bibliography' only works with a very narrow window, and gets odd as you stretch it larger.

I imagine most people will have their window larger enough that 'Bibliography' is an immediate problem.
On a cellphone (at least mine), there is no issue.

I have created a github repository of my blog, so that you are able to see exactly what it is I am doing, which is nothing at all complex.
https://github.com/warmstarter/namelessblog

Please let me know if you have any questions that I can help with.

I understand this may not be solely (or at all an ablog) issue, but instead a bibtex issue.
I will be opening up a bug for them as well, and will follow-up with a link to that to help with communication.

### Screenshots

![Screenshot 2022-10-16 8 47 01 AM](https://user-images.githubusercontent.com/79870389/196036200-4505e5a3-3684-4de1-bd22-df924f811d57.png)
![Screenshot 2022-10-16 8 46 56 AM](https://user-images.githubusercontent.com/79870389/196036201-1f5b5265-1dea-4be6-a83d-6ad6bbd54fdf.png)
![Screenshot 2022-10-16 8 46 49 AM](https://user-images.githubusercontent.com/79870389/196036203-41245b7e-b855-4153-acae-df88f88e43ec.png)

### System Details

Linux ip-172-26-15-157 4.19.0-20-cloud-amd64 #1 SMP Debian 4.19.235-1 (2022-03-17) x86_64 GNU/Linux
Debian 10.13 (Completely updated)
Python 3.7.3-2
Virtualenv (see requirements.txt in included repository for more.)

### Installation method

pip

**Comment by warmstarter** [comment]
The Bibtex issue has been opened at:

https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/318

**Comment by nabobalis** [comment]
I try to avoid pinning versions of packages especially since I don't test with `sphinxcontrib-bibtex`.

I will leave this open to act as a guide for others if they have the same issue.
