### ISSUE TITLE
make github buttons smaller

### ISSUE THREAD

**Issue by aguang** [sunpy/ablog#17]
Is there anyway to make the github buttons (i.e. watch, follow, etc.) smaller through ablog? They are all on the large settings. I can see on the alabaster theme that you can go in and modify the template for `about.html`, but I'm not sure how you would go about it with ablog.

**Comment by nabobalis** [comment]
You can overwrite the CSS for those using the .gh-btn or .github-btn-large. Otherwise the buttons aren't really controlled by Ablog itself.

**Comment by aguang** [comment]
thanks you for the suggestion. I tried that but it didn't work, I think because the alabaster theme puts in the iframe html code in the about.html page and I don't think the custom.css overrides the style.css from the github buttons. Regardless I just changed the about.html and put it in _templates which worked fine, so I'll close this.
