### ISSUE TITLE
pdf build fails (on ReadTheDocs)

### ISSUE THREAD

**Issue by AlbertMietus** [sunpy/ablog#18]
When using the **pdf** builder, there appears to be a bug. See the log on RTfD.org

> Exception occurred:
>  File "/home/docs/checkouts/readthedocs.org/user_builds/docideas/envs/latest/lib/python3.5/site-packages/ablog/post.py", line 354, in process_posts
>    stdlabel = env.intersphinx_inventory.setdefault('std:label', {})
> AttributeError: 'BuildEnvironment' object has no attribute 'intersphinx_inventory'
-- http://readthedocs.org/projects/docideas/builds/7112291/

The html-builder works fine! 
As this project has both *normal* articles and *blog-post*, i like to have a "paper" (pdf) build too. 

Details: (also see the log-link above)
* Python-3.5 ( no newer one on RTFD
* Latest ablog version (0.9.2)

Thanks for ablog & thanks for the fix!

Note: I can't build pdf locally, so can give more details

**Comment by nabobalis** [comment]
Does this still occur?

**Comment by palkeo** [comment]
I just had the same problem when building HTML, that was because I didn't have "sphinx.ext.intersphinx" in the sphinx extensions list (in conf.py)

**Comment by nabobalis** [comment]
`sphinx.ext.intersphinx` should be set by default by the start.py file. I am not sure if this is a config issue on our side or not but I will close this. If you want to reopen it, go ahead.
