### ISSUE TITLE
Set the `ablog/` documentation to default to `stable/` instead of `latest/`

### ISSUE THREAD

**Issue by choldgraf** [sunpy/ablog#181]
### Describe the feature

I was recently confused because I visited the ABlog documentation and saw that [there was a blog post about the new release of ablog](https://ablog.readthedocs.io/en/latest/release/ablog-v0.11-released.html). However, I couldn't find it on PyPI or anywhere else.

After looking again, I realized that I was on an unreleased `latest/` version of the docs, and I guess the actual release hadn't yet been made.

### Proposed solution

I think the documentation should point to the latest _released_ version, instead of the version on `main/`. I think having a `latest/` version is still a good idea, just not the default. This should help clarify confusion between new changes and released reality.

(as an aside, the date of that blog post was also July 2022, which I thought might be a bug)

**Comment by nabobalis** [comment]
I have changed the default version on RTD to be stable.

Hopefully that works!

**Comment by choldgraf** [comment]
Yep - can confirm that it now defaults to stable 🙂 thanks!
