### ISSUE TITLE
Only some `ablog` sidebar templates have the `.ablog-sidebar-item` class

### ISSUE THREAD

**Issue by choldgraf** [sunpy/ablog#186]
### Describe the bug

Trying out the new pre-release now. One thing I noticed is that some sidebar components (like the tag cloud) have a generic `ablog-sidebar-item` class:

![image](https://user-images.githubusercontent.com/1839645/209975466-b69e0c76-8f9c-4794-8ba6-090e05609067.png)

While others do not:

![image](https://user-images.githubusercontent.com/1839645/209975541-2fa204db-8797-4d91-bc70-427d7303d84b.png)

Do you think you could standardize this so that any template component that is in the sidebar also has this class?  It would make it easier to standardize behavior with CSS.

### Classes I've had to specify

Here's a list of classes I had to special-case in CSS to get this to work, and that I think could be good targets to add the generic class:

- `.ablog__languages`
- `.ablog__locations`
- `.ablog__postcard`

**Comment by nabobalis** [comment]
Would https://github.com/sunpy/ablog/pull/187 solve this for you?
