### ISSUE TITLE
Option for absolute URLs in feed

### ISSUE THREAD

**Issue by davidfischer** [sunpy/ablog#19]
The atom feed has relative URLs when when there are internal links to other posts or images. Some services, however, need the URLs in a feed to be fully qualified to work correctly. For example, [Mailchimp's RSS mailer needs absolute link and image paths](https://kb.mailchimp.com/templates/code/common-html-mistakes#Images,-Links,-and-Graphics). There should be a way to require all paths to be fully qualified in the atom feed especially since there is already the `blog_baseurl` setting.

I'm not super familiar with sphinx translators but it seems like it should just be a matter of setting one of those up correctly since sphinx is already translating the relative path from the feed back to where the posts/images are. I will see if I can resolve this when I get a chance.

**Comment by davidfischer** [comment]
The more I think about this, the more I think this is Mailchimp's bug and not an issue with ablog. I'm still going to take a look at this but it's possible the fix lives as another extension.

**Comment by davidfischer** [comment]
I ended up working around this issue.

**Comment by nabobalis** [comment]
What did you do in the end?

**Comment by davidfischer** [comment]
I wrote a small sphinx extension to create a modified Atom feed after the previous one's generation. https://github.com/rtfd/blog/pull/37
