### ISSUE TITLE
Ability to create a Sitemap

### ISSUE THREAD

**Issue by nabobalis** [sunpy/ablog#2]
Maybe based off [this.](https://bitbucket.org/emacsway/emacsway/src/default/_sitemaps.py?fileviewer=file-view-default)

**Comment by SilverRainZ** [comment]
Why not use sphinx-sitemap?

**Comment by nabobalis** [comment]
Looks like that would work really well.

**Comment by SilverRainZ** [comment]
This one can be closed too?
