### ISSUE TITLE
Sphinx linkcheck builder exception: 'BuildEnvironment' object has no attribute 'intersphinx_inventory'

### ISSUE THREAD

**Issue by choldgraf** [sunpy/ablog#205]
### Describe the bug

It seems like here `ablog` assumes that `intersphinx_inventory` exists:

https://github.com/sunpy/ablog/blob/bcbb7c5de74abf8e1b5474e59f94de5ec8641e71/src/ablog/post.py#L420-L422

But I believe that if somebody is running the `linkcheck` builder, it won't exist yet. I think that if you just added a quick check for the presence of that attribute it would be enough.

### To Reproduce

I was able to reproduce this by trying to build the `pydata-sphinx-theme` docs with the `linkcheck` builder. It resulted in the following error:

```
Extension error (ablog.post):
Handler <function process_posts at 0x7ff66392f280> for event 'doctree-read' threw an exception (exception: 'BuildEnvironment' object has no attribute 'intersphinx_inventory')
```

### Installation method

pip

**Comment by nabobalis** [comment]
v0.11.0rc3 should be out soon with this bugfix, please report how it goes!
