### ISSUE TITLE
Using „ABlog“ as tag value

### ISSUE THREAD

**Issue by Marrin** [sunpy/ablog#241]
### Describe the bug

„ABlog“ apparently can't be used as a tag value.  I've recently moved from Tinkerer to ABlog and wrote a blog post about the switch.  It's tagged with „Tinkerer“ and „ABlog“ like this:

```rst
.. post::
    :category: Blog
    :tags: Tinkerer, ABlog
```

„ABlog“ doesn't appear in the tag cloud at all.  It is in the „Tags:“ line for the article, but just as ordinary text, not as link to a page with a post listing of all posts tagged „ABlog“.

**Comment by SilverRainZ** [comment]
IMO it is not a bug. You don't specify a date for the post, it is treated as a draft, so no tags generated, You may have written other posts tagged "Tinkerer" so the tag is generated.


Give it a date, you should see the tag is no longer ordinary text:

```rst
.. post:: 2024-01-02
    :category: Blog
    :tags: Tinkerer, ABlog
```

**Comment by SilverRainZ** [comment]
@nabobalis I think this one can be closed now :D
