### ISSUE TITLE
KeyError 'refdoc' when missing references

### ISSUE THREAD

**Issue by Anntoin** [sunpy/ablog#26]
I'm seeing the same issue as noted in https://github.com/abakan-zz/ablog/issues/75

Seems to be related to this:
```python
def missing_reference(app, env, node, contnode):

    target = node['reftarget']
    return _missing_reference(app, target, node['refdoc'],
contnode, node['refexplicit'])
```
https://github.com/sunpy/ablog/blob/master/ablog/post.py#L458

If I change `node['refdoc']` to something like `node.source` it works - I'm not sure if this is correct behaviour however.

Haven't been able to reproduce a minimal example yet, it's just happening in my main env, any pointers appriciated. Using sphinx 1.7.6, ablog 0.9.2

**Comment by Anntoin** [comment]
Unfortunately I can't share my env (work), but have done a little more digging.

What I'm seeing is that `revise_pending_xrefs` isn't being called when I run a build, so `refdoc` isn't being set on any nodes. In fact it looks like the `doctree-resolved` event isn't being emitted at all, so `process_postlist` isn't called which should call `revise_pending_xrefs`.

As `doctree-resolved` is a core sphinx event I'm sure there's something funky up with the version of sphinx I'm using, but it'd be good if the extension handled this gracefully too.

Not sure what the best behaviour would be but should `revise_pending_xrefs` be handled as part of `missing_reference` (or a different event?) or just fall back if `refdoc` isn't found, e.g. to `node.source`.

**Comment by Anntoin** [comment]
Actually, looks like the problem is due to event ordering. If I change `node['refdoc']` to `node.source` that allows the build to proceed, so afterwards `doctree-resolved` is emitted and `process_postlist` **is** called.

**Comment by nabobalis** [comment]
So I should just make that change and that should fix whatever this bug is?

**Comment by Anntoin** [comment]
Just updating https://github.com/sunpy/ablog/blob/master/ablog/post.py#L459 to
`return _missing_reference(app, target, node.get('refdoc'),` fixes the immediate issue for me. There's more going on with missing_references and postlists that probably needs looking into at some point - but I'll raise an issue if I spot anything.

**Comment by nabobalis** [comment]
I've made the change in PR #28, but I also changed the other dictionary index just in case. They probably should be changed in other places. But I will do a release `0.9.3` for now to make this change.

**Comment by Anntoin** [comment]
Awesome, thanks :+1:

**Comment by nabobalis** [comment]
I just pushed the update to PyPi. Conda will take a while to update.

**Comment by Anntoin** [comment]
Just to confirm, 0.9.3 is working for me. Getting warnings for missing references but builds succeed. Thanks for the quick turn-around
