### ISSUE TITLE
WARNING: the ablog extension does not declare if it is safe for parallel reading

### ISSUE THREAD

**Issue by felixhummel** [sunpy/ablog#264]
### Describe the bug

Running `sphinx-build` with multiple jobs results in the following warning:

```
WARNING: the ablog extension does not declare if it is safe for parallel reading, assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
```

I don't know if ablog supports parallel reading.

If so, a simple change to the [extension metadata](https://www.sphinx-doc.org/en/master/extdev/index.html#extension-metadata) should suffice.

### To Reproduce

sphinx-build -j4 -b html -d _build/doctrees . _build/html

**Comment by plaindocs** [comment]
Looks like this would be sufficient if it is https://github.com/agronholm/sphinx-autodoc-typehints/commit/c4657bc57a290a79605ed86398db28419aabfbb9

**Comment by liborjelinek** [comment]
Just a follow-up for those reading this issue: Ablog is NOT parallel read safe and declares it now (see #297).
