### ISSUE TITLE
Tags in tag cloud has same font-size 

### ISSUE THREAD

**Issue by SilverRainZ** [sunpy/ablog#267]
### Describe the bug

Although each tag has a corresponding CSS class ["ablog-cloud-%d"](https://github.com/sunpy/ablog/blob/6b867ad7355c6020f5c962b7e9f98efb7051964b/src/ablog/templates/ablog/tagcloud.html#L7) to indicate the relative size, but there is no any CSS style defined, can we have a default style?

### To Reproduce

Just see tag cloud of https://ablog.readthedocs.io/en/stable/

### Screenshots

![image](https://github.com/sunpy/ablog/assets/8090459/3c919edf-3809-45cd-879f-f72d502afed6)

### Installation method

pip

**Comment by SilverRainZ** [comment]
I found that [other ABlog instance](http://blog.marc.rintsch.de/index.html) has a normal tag cloud, I don't know what's the difference between them.

![图片](https://github.com/sunpy/ablog/assets/8090459/a9a51f9a-5dde-4d2c-8472-0938c3cdcfba)

**Comment by nabobalis** [comment]
Is the problem the line break after each tag?

**Comment by SilverRainZ** [comment]
I think not, the problem is https://ablog.readthedocs.io/en/stable/ lacks a `<style>` tag:

![2024-01-03_004036](https://github.com/sunpy/ablog/assets/8090459/5dac9f50-0108-446a-90c8-cfbb502c1cad)

but http://blog.marc.rintsch.de/index.html has:

![2024-01-03_004015](https://github.com/sunpy/ablog/assets/8090459/26958da5-4816-4752-bfe8-6bbf170bfa91)

**Comment by nabobalis** [comment]
We can add a stylesheet in ablog. I wonder if ablog used to do that and I forgot.

**Comment by SilverRainZ** [comment]
Yes, the stylesheet is removed in https://github.com/sunpy/ablog/commit/6626ad677b1cdc917d9ee94c50e5203ecccf0823#diff-706024afeaaff863be49aa72c4f98a21123d350d433a09f6d2d70ba597b4cbba , and possibly by accident

**Comment by nabobalis** [comment]
Ah yeah, good spot. I removed it and forgot to add anything back in an actual css file.

**Comment by SilverRainZ** [comment]
So you prefer to add a standalone CSS file than an embed style tag?

**Comment by nabobalis** [comment]
I would go towards that.

**Comment by SilverRainZ** [comment]
If you are busy, I can help with this :-)

**Comment by nabobalis** [comment]
I won't say no to help.
