### ISSUE TITLE
Use list rather than set when stripping values for postlist

### ISSUE THREAD

**Issue by JoeZiminski** [sunpy/ablog#279]
### Describe the feature

We have multiple authors on blog posts and would like to specify their order as appears on the postlist. At present we are using the `:author:` key in the blog post and ` :format: {title} by {author}, {date}` in the `index.rst`. Using this approach, the list of authors is randomised on the blog index.

When building the postlist, [this function](https://github.com/sunpy/ablog/blob/a85a561a19007ff885b6c0d1a3b2dd7ec504f1c6/src/ablog/post.py#L41) strips the value names for display and returns as a set. Returning as set results in the order being randomised. If instead a list is returned, the order as specified in the blog header is maintained on the postlist.

Can this be changed to return a set, or at least changed only for author lists? Maybe there is another way to specify the authors in a non-random manner.

### Proposed solution

[`_strip`](https://github.com/sunpy/ablog/blob/a85a561a19007ff885b6c0d1a3b2dd7ec504f1c6/src/ablog/post.py#L41) returns a list instead of set.

I'm happy to make a PR but unsure of any unintended consequences. Scope of change could be limited by having a separate function `_strip_list` that returns as list, and is used only in the [author field](https://github.com/sunpy/ablog/blob/a85a561a19007ff885b6c0d1a3b2dd7ec504f1c6/src/ablog/post.py#L117).

**Comment by nabobalis** [comment]
> I'm happy to make a PR but unsure of any unintended consequences. 

I think it makes more sense to keep the order of any lists created by an author. 
So we can just have it return the list as is instead of a set for everything.

**Comment by JoeZiminski** [comment]
Great thanks @nabobalis I will make a PR now.
