### ISSUE TITLE
Theme support for partial overwriting Ablog templates is maybe broken

### ISSUE THREAD

**Issue by liborjelinek** [sunpy/ablog#294]
### Describe the bug

I am trying to use recent template rework for overwriting `ablog/postcard.html` only but keep the rest of Ablog templates. However, I can't find out the way to manage it. **Is there some known theme which ships their Ablog templates?** Maybe it would help me.

### To Reproduce

However, I suspect that this template rework is broken.

1. Because I want to "hide" only some Ablog templates, I don't set `skip_injecting_base_ablog_templates = True`.
2. Under my theme folder, I created `ablog/postcard.html` 
3. In my `theme.toml` I added
   ```
   [ablog]
   inject_templates_after_theme = true
   ```
4. My theme's `ablog/postcard.html` is never used.

There is at least one reason why not. Consider the [relevant excerpt from Ablog](https://github.com/sunpy/ablog/blob/main/src/ablog/__init__.py#L125):

```
    try:
        after_theme = theme.get_config("ablog", "inject_templates_after_theme", False)
    except ThemeError:
        after_theme = False
    if after_theme:
        loaders.append(SphinxFileSystemLoader(get_html_templates_path()))
    else:
        loaders.insert(templatepathlen, SphinxFileSystemLoader(get_html_templates_path()))
```

The `theme.get_config("ablog", "inject_templates_after_theme", False)` call raises `ThemeError` exception with message `Theme configuration sections other than [theme] and [options] are not supported`.

This exception is incorrectly interpreted as missing default value and code flow went to `else` block.

But as the message said, the Sphinx's `Theme.get_config()` doesn't allow reading custom sections like `[ablog]` from `theme.toml` files. Unfortunately in such case, it raises ThemeError too.

(Excerpt from [`Theme.get_config()`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/theming.py#L114):)

```
           msg = __(
                'Theme configuration sections other than [theme] and [options] '
                'are not supported (tried to get a value from %r).'
            )
            raise ThemeError(msg)
```

### System Details

Sphinx==8.1.2
ablog==0.11.11

**Comment by liborjelinek** [comment]
FYI @pradyunsg and @choldgraf

**Comment by liborjelinek** [comment]
If you confirm it's a bug, I will prepare a pull request which

- rename `inject_templates_after_theme` to `ablog_inject_templates_after_theme`
- modify Ablog setup callback to expect it in theme.toml/ini `[options]` section, not `[ablog]`
- add tests
- update docs with new conf.py's `skip_injecting_base_ablog_templates` and theme.toml's `ablog_inject_templates_after_theme` (both are missing yet)

**Comment by nabobalis** [comment]
Not going to say I understand sphinx but if those changes fix it, happy to accept the PR.
