### ISSUE TITLE
Fix sidebars CSS naming

### ISSUE THREAD

**Issue by liborjelinek** [sunpy/ablog#296]
### Describe the bug

In recent template rework, we improved also styling options by adding sidebars into `ablog-sidebar-item ablog__<template_name>` containers. For example, the `recentposts.html` template is wrapped in `<div class="ablog-sidebar-item ablog__recentposts">`.

But some sidebars don't follow this naming rule (likely by typo?):

- `archives.html` has `ablog-sidebar-item ablog__archive`
- `categories.html` has `ablog-sidebar-item ablog__category`
- `tagcloud.html` has `ablog-sidebar-item ablog__tags`

IMHO, it's still a time to name it properly. Is anybody using it already? It looks not yet.

Anyway, I suggest to fix it in backward-compatible manner. E.g., `ablog-sidebar-item ablog__tags` will become `ablog-sidebar-item ablog__tagcloud ablog__tags`.

**Comment by nabobalis** [comment]
Yeah, I don't mind fixing it in a non-backwards compatible way.
