### ISSUE TITLE
Ablog isn't safe for parallel reading

### ISSUE THREAD

**Issue by liborjelinek** [sunpy/ablog#297]
### Describe the bug

It looks Ablog isn't safe for parallel reading (introduced in ad5665a).

But it's safe for parallel writing (4f9ae64).

Both changes are recent (summer this year) and made by @nabobalis :-) What lead you to these changes? :-)

I've add `-j auto` to sphinx-build (use as many CPU cores as possible) recently and noticed Ablog doesn't detect any single post and all `postlists` were empty. With `-j 1` (use single core, default value) Ablog works again.

It would be nice to fix it, but I am unsure about the reasons. As "workaround" I suggest change to `"parallel_read_safe": False, "parallel_write_safe": True`.

**Comment by nabobalis** [comment]
I just marked it safe since I thought it was.
