### ISSUE TITLE
To ignore _version.py?

### ISSUE THREAD

**Issue by liborjelinek** [sunpy/ablog#300]
### Provide a general description of the issue or problem.

Then developing on Ablog, I install it locally (in editable mode) with `pip install -e .`. It creates `src/ablog/_version.py` with the content similar to

```
# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple, Union
    VERSION_TUPLE = Tuple[Union[int, str], ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = '0.11.12.dev4+gc17d644'
__version_tuple__ = version_tuple = (0, 11, 12, 'dev4', 'gc17d644')
```

I am not aware of Setuptools stuff at all. **Is it only me or should this file be gitignored as noted in the comment?**

**Comment by nabobalis** [comment]
Odd, it should be git ignored but it isn't. I will add that to my CI PR.
