### ISSUE TITLE
Bug in fontawesome_link_cdn handling at install time

### ISSUE THREAD

**Issue by PhilipMay** [sunpy/ablog#35]
When I use `ablog start` and say I want to have fontawesome then abog generates this line in `conf.py`: `fontawesome_link_cdn = True`

This leads to this line in the generated html code: `<link href="True" rel="stylesheet">`

This is a bug...

Thanks
Philip

**Comment by rayalan** [comment]
Some quick notes on this:
1. The primary issue looks like documentation isn't clear that this value should be the url location of the CDN, not `true`. 
2. A secondary issue is that there's minimal validation of config values, so there's not much warning or visibility of something is wrong.
