### ISSUE TITLE
`generate_atom_feeds()` raises StopIteration

### ISSUE THREAD

**Issue by baylessj** [sunpy/ablog#43]
Original issue was opened on Sphinx as sphinx-doc/sphinx#6722

The offending line is this: https://github.com/sunpy/ablog/blob/d148cf469d3ffa1fcac48c3032ea5192b4e19ae0/ablog/post.py#L607

Not entirely sure what causes the url to be `None`, I'll do some more digging to see if it's an issue with my project's configuration or not. My hunch is that it is due to my combination of Python version and OS, the other developers on my team are able to build fine.

## Project

https://github.com/purduesigbots/pros-docs

## Software Versions

- Python: 3.7.3
- OS: Pop!_OS 19.04

**Comment by nabobalis** [comment]
What version of ablog are you using? Can you try with master? It is a Python 3 only version that I hopefully plan to release this year.

**Comment by baylessj** [comment]
0.9.4, I'll upgrade to 0.9.5 and see if that solves the issue.

**Comment by baylessj** [comment]
Upgraded, issue still occurs. Will look more into the cause.

**Comment by nabobalis** [comment]
You will have to install the version from master, its 0.10dev.

**Comment by baylessj** [comment]
Makes sense. Installed from source, version num is now `0.9.6.dev2+gd148cf4`. Still getting the same error output.

**Comment by baylessj** [comment]
Adding the `blog_baseurl` string to the `conf.py` for the project stopped the error, which is good. I was not under the impression from ablog's documentation that this was a required parameter though, and I hadn't noticed this being necessary before, so that is odd. Should I consider this option to be a required option for ablog usage, or is something else causing this symptom?

**Comment by nabobalis** [comment]
Yeah it probably should be.

**Comment by nabobalis** [comment]
Actually now I recall. I think there is an open PR to fix this.

**Comment by baylessj** [comment]
Are you referring to #38? That seems related, but I can't really tell from the modifications to the code there if it adds a default `baseurl` value or if it requires the value

**Comment by nabobalis** [comment]
If I recall, I think it makes it require it.

**Comment by nabobalis** [comment]
There probably should be a base default

**Comment by baylessj** [comment]
I agree, a default would be nice to have. I'm not particularly interested in having an atom feed in my project's blog and it would be nice to not have to specify additional options for that. 

Looks like jekyll just sets the baseurl value in their conf file to an empty string, do you think the same approach would work here?

**Comment by nabobalis** [comment]
Well it's better than being None

**Comment by baylessj** [comment]
Agreed. I can open a PR for this if you'd like, or would you prefer that this modification be a part of #38?

**Comment by nabobalis** [comment]
Probably makes more sense to be part of #38, could you leave a comment on that PR about this?
