### ISSUE TITLE
Exception occurred:   File "C:\Users\simon\Anaconda3\lib\site-packages\sphinx\builders\html.py", line 656, in gen_pages_from_extensions     for pagename, context, template in pagelist: RuntimeError: generator raised StopIteration

### ISSUE THREAD

**Issue by simonm3** [sunpy/ablog#44]
Added to my conf.py exactly what it says in the getting started instructions. I get the error below when I do the sphinx build. I am on windows python 3.7.

Exception occurred:
  File "C:\Users\simon\Anaconda3\lib\site-packages\sphinx\builders\html.py", line 656, in gen_pages_from_extensions
    for pagename, context, template in pagelist:
RuntimeError: generator raised StopIteration

**Comment by nabobalis** [comment]
I assume this is version 0.9.X of ablog? 

I think this is the same issue as https://github.com/sunpy/ablog/issues/43 which hopefully will be fixed in 0.10 of the library soon(TM). Sorry for causing the problem.
