### ISSUE TITLE
Missing doc page about blog sidebars

### ISSUE THREAD

**Issue by denisrosset** [sunpy/ablog#51]
The manual, on the page https://ablog.readthedocs.io/ mentions the blog sidebars, but the link is dead:

https://ablog.readthedocs.io/manual/ablog-configuration-options/#sidebars

**Comment by nabobalis** [comment]
Yeah it should be https://ablog.readthedocs.io/manual/ablog-configuration-options.html#blog-sidebars

There might be more links that need fixing. Thanks for finding it.

**Comment by nabobalis** [comment]
I just changed the urls, so hopefully that will work now. I think there is a config settings missing since the .html shouldn't need to be there but I can worry about that later.

**Comment by denisrosset** [comment]
Got it thanks! and I just added `recentposts.html` to my sidebar, after adapting to the `guzzle` theme conventions. Thanks a lot!

**Comment by nabobalis** [comment]
Yeah I'm not sure that html should be in the url and it wasn't before. A regression somewhere during when I was updating the library.
