### ISSUE TITLE
Error message shows in html output

### ISSUE THREAD

**Issue by mi24datn** [sunpy/ablog#56]
If you include a line containing only a period or dash, the build succeeds, even with warnings as errors on, but the following error text incorrectly appears in the html output:

"Possible title underline, too short for the title. Treating it as ordinary text because it’s so short."

A web search of this string will turn up several unlucky ablog users to whom this has happened on their live site.

To reproduce:

```
.. post:: 17 Feb, 2020
   :tags: ablog, error, test
   :author: mi24datn
   :nocomments: 

This is the title
-----------------

And this is the post.
-
```

**Comment by nabobalis** [comment]
Thanks for the report, I will investigate this and see if i  can patch it.

**Comment by nabobalis** [comment]
Hi @mi24datn, sorry it took me this long to get back to you.
I was looking at this and using that example or other variations, I can get:

```python
/home/nabil/GitHub/ablog/docs/release/test.rst:7: WARNING: Title underline too short.

This is the title
-------------
/home/nabil/GitHub/ablog/docs/release/test.rst:10: WARNING: Title underline too short.

And this is the post.
---------
/home/nabil/GitHub/ablog/docs/release/test.rst:10: WARNING: Title underline too short.

And this is the post.
---------
```

in my build log but the html page looks like this:
![Screenshot from 2020-04-05 14-03-11](https://user-images.githubusercontent.com/1392107/78499044-380ccb00-7746-11ea-94a8-dd617c4b4407.png)

I seem to be unable to replicate it right now.
Can you tell me your theme, ablog and sphinx versions?

**Comment by nabobalis** [comment]
I will close this issue for now, if it still happens, can you please open an issue with a link or a broken example please?
