### ISSUE TITLE
missing reference not shown in post.py

### ISSUE THREAD

**Issue by bradporter** [sunpy/ablog#62]
User error in references causes a error in missing_reference() in post.py.  There is no indication of which reference is missing or has an error, which can result in a lot of frustration when there are a lot of references.  It can be resolved with the addition of the print statement below:

`def missing_reference(app, env, node, contnode):`
`    target = node['reftarget']`
`    print('error, missing reference: ',target, contnode)`
`    return _missing_reference(app, target, node['refdoc'],`
`                              contnode, node['refexplicit'])`

**Comment by nabobalis** [comment]
Sorry for not replying, do you have an example of this failing?

Without more details on what triggers this and what user error is causing this, fixing this is tricky.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by bradporter** [comment]
I was suggesting adding the print statement because it shows where the errors are, which are very tedious to find if there are a lot of references.  My recollection is this error was just a typo in the reference.

**Comment by nabobalis** [comment]
Ah I see, I will add a `logging.warning(f'error, missing reference: {target}, {contnode}') in that function to raise some text for this.
