### ISSUE TITLE
Consider using field lists for post metadata

### ISSUE THREAD

**Issue by choldgraf** [sunpy/ablog#68]
In Sphinx, you can attach document-level metadata at the top of an rST file via a field list (https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html). What do folks think about also allowing field lists to define the mechanism for identifying blog posts (in addition to directives). Using file-wide metadata is the common way that this is done in other blogging engines (e.g. [Jekyll front matter](https://jekyllrb.com/docs/front-matter/)) and could be a nice way to separate out metadata about the post from the post content.

I _think_ it should be pretty do-able by adding a transform that runs *before* the `doctree-read` event ([see here for reference on event timing](https://www.sphinx-doc.org/en/master/extdev/appapi.html#sphinx-core-events)) and checks the document metadata for something like:

```
:blog: True
```

and if it finds that, it adds a `PostNode` to the page.

Then you could have post-level metadata at the top of the page so it could look something like:

```
:blog: True
:author: My Name
:date: 2020-09-11
...etc

My Title
========

...
```

Curious what folks think about that...

**Comment by choldgraf** [comment]
cc @cjsewell who may have ideas there too?

**Comment by nabobalis** [comment]
This sounds like a good idea, how would this interact with the metadata defined in a `post` block?

**Comment by choldgraf** [comment]
hmm, I'd imagine we could do something like:

- If post metadata is found in a field list, search the document for a `post` node.
- If found, update the post node with metadata from the field list.
- If not found, add a new post node.
- (alternatively, make them mutually exclusive)

does that make sense?

**Comment by chrisjsewell** [comment]
Heya, I guess you could merge the two, during the directive run or in a transform, picking either as the "preferential" source.

For context, this package looks pretty cool, and we are thinking about integrating it, in some form, into jupyter-book 😄: https://github.com/executablebooks/jupyter-book/issues/900#issuecomment-688251127

**Comment by chrisjsewell** [comment]
But really, if it was up to me lol, I would just ditch the `post` directive entirely, because directives are syntactically meant to specify block level entities within a page, whereas the data actually being specified here is page level metadata

**Comment by nabobalis** [comment]
Ditching it would be a major breaking change which I am reluctant to do/support.

**Comment by nabobalis** [comment]
But on supporting both, I would be in favour of.

**Comment by chrisjsewell** [comment]
Oh yeh absolutely, I just wanted to mention my ideal solution. Again for context, with jupyter-book and its dependancies (myst-parser and myst-nb) we read the metadata and store that in the AST in the same way as using the initial field list in rST. So these are equivalent:

rST:

```restructuredtext
:title: my title

text
```

Markdown:

```markdown
---
title: my title
---

text
```

Notebook:

```json
{
 "metadata": {
   "title": "my title" 
 },
 "cells": [
  {
    "cell_type": "markdown",
    "source": "text"
  }
 ]
}
```

**Comment by choldgraf** [comment]
@chrisjsewell do you know if it's possible to call a Directive from within a transform? Then we could check for front matter yaml in the transform stage and call the Post directive with the proper arguments to make sure all of the same defaults and type checks were used.
