### ISSUE TITLE
Missing github tag?

### ISSUE THREAD

**Issue by rgrinberg** [sunpy/ablog#7]
I see ablog 0.8.4 in pip, but only 0.8.3 exists in the releases for this project.

**Comment by nabobalis** [comment]
Looks like the old versions were not always tagged. 

I am a bit behind and need to tag a new release  and send it to pip.

**Comment by rgrinberg** [comment]
That would be lovely! By the way, I'm packaging up ablog for conda https://github.com/conda-forge/staged-recipes/pull/5271

If you use conda, and want to help out. I can list you there as a maintainer as well.

**Comment by nabobalis** [comment]
That would be great! It was on the to-do list once I got the pypi release out!

**Comment by nabobalis** [comment]
I just released 0.9.0 into the world.
