### ISSUE TITLE
Test writing blog posts in markdown with MyST

### ISSUE THREAD

**Issue by Cadair** [sunpy/ablog#70]
Since #69 we should be able to support markdown it would be good to test this to make sure it works and to ensure that it continues to work in the future.

**Comment by kakirastern** [comment]
Am testing this on the https://github.com/sunpy/sunpy.org side now

**Comment by kakirastern** [comment]
Let me try and open a PR with a new `markdown` file with the appropriate metadata... Alos, let me try using the `blog: true` flag for this.

**Comment by nabobalis** [comment]
Also we want documentation added to the manual in the docs on how to use markdown files, setup the config and how to use the new frontend matter (with markdown, with rst, with the config option).

Maybe look at removing the config option as well.

**Comment by kakirastern** [comment]
Yeah, agreeing 💯 %
