### ISSUE TITLE
Atom feed ID field is constant

### ISSUE THREAD

**Issue by loebl** [sunpy/ablog#82]
### Description

The feed:id field is always set to `http://lernfunk.de/media/654321` (https://github.com/sunpy/ablog/blob/debbd32bd390bc29cd5e614dd251bd0ce2cfb36d/ablog/post.py#L707)

I haven't run extensive tests, but according to RFC 4287 (4.2.6) it should be a unique string per feed, so in the current form there could potentially arise problems when multiple ablog based sites are subscribed. (In firefox with the Feedbro extensions I haven't seen any issues though).

### Expected vs Actual behavior

I would expect it to be configurable via conf.py. Possible conf name for example `blog_feed_id`.

I think a sane default value could be the same as the `blog_baseurl` (which needs to be set for feeds to enable and should be sufficiently unique enough for most cases).

### Steps to Reproduce

Enable the feeds by setting a `blog_baseurl` and check the id field for the feed in the atom.xml

### System Details

- Python: 3.7.3 (Debian Buster)

Python venv with the following packages (shortened pip list)
```
Package                       Version
----------------------------- ---------
ablog                         0.10.11
docutils                      0.16
feedgen                       0.9.0
invoke                        1.4.1
pip                           20.2.2
Sphinx                        3.2.1
```

**Comment by nabobalis** [comment]
Thanks for reporting this, would replacing it with a uuid4 string be enough?

**Comment by nabobalis** [comment]
I have changed this and made a new release: v0.10.12

**Comment by loebl** [comment]
Thanks for the quick response.

The Atom spec expects an IRI, an Internationalized Resource Identifier, which is basically the same as an URI, but allows characters from the Universal character set. Though additionally the Atom spec also states that it should not be expected that the IRI points to actually something ("Atom Processors MUST NOT assume it can be dereferenced.").

So yeah, I guess baseurl should be correct regarding the spec, and should also be sufficiently unique.
