### ISSUE TITLE
Missing reference handler does't handle `blog-feed` reference correctly

### ISSUE THREAD

**Issue by SilverRainZ** [sunpy/ablog#90]
https://github.com/sunpy/ablog/blob/211b3b6887f31d0b9ae7199f8d702b5e56947447/ablog/post.py#L548-L556

The ``get_relative_uri`` method of HTML builder always add a ".html" suffix to URI, so ``atom.xml`` becomes ``atom.xml.html``.

**Comment by nabobalis** [comment]
Just to double check, this means that an `atom.xml` url actually resolves to `atom.xml.html`?

**Comment by SilverRainZ** [comment]
> Just to double check, this means that an `atom.xml` url actually resolves to `atom.xml.html`?

Yes.

**Comment by nabobalis** [comment]
At least for the docs we are building on the project, the atom.xml url works: https://ablog.readthedocs.io/blog/atom.xml 

What am I missing?

**Comment by SilverRainZ** [comment]
Only occurs when you use ``:ref:`blog-feed` ``, in the ablog, it use the URL you said directly.

**Comment by nabobalis** [comment]
Ok, I will have a play around.

**Comment by nabobalis** [comment]
I have added a workaround to remove the .html for that tag and added it to the docs so I can check it in future.

**Comment by SilverRainZ** [comment]
More details:

`HTMLBuilder`'s ``get_relative_uri`` is inherited from `Builder`:

```python
    def get_relative_uri(self, from_: str, to: str, typ: str = None) -> str:
        """Return a relative URI between two source filenames.

        May raise environment.NoUri if there's no way to return a sensible URI.
        """
        return relative_uri(self.get_target_uri(from_),
                            self.get_target_uri(to, typ))
```

But ``HTMLBuilder`` overrides the impl of ``get_target_uri``:

```python
    def get_target_uri(self, docname: str, typ: str = None) -> str:
        return quote(docname) + self.link_suffix
```

Where link_suffix is ".html".

**Comment by nabobalis** [comment]
I just added a rough workaround here: https://github.com/sunpy/ablog/pull/94/files#diff-f4d8728fd1bca178eb101f7635407e0b843bb4d18d2df7230352f1d5583e4f39R556-R558

**Comment by nabobalis** [comment]
Will be in the new version v0.10.14 to be out in an hour.
