### ISSUE TITLE
Atom feeds fail W3C validation

### ISSUE THREAD

**Issue by rpatterson** [sunpy/ablog#91]
### Atom feeds fail W3C validation

The generated Atom feeds don't pass W3C validation

### Expected vs Actual behavior

Expected behavior: Generated Atom feeds pass W3C valdation
Actual behavior: Generated Atom feeds fail W3C valdation

```
This feed does not validate.

line 9, column 2: Duplicate alternate links with the same type and hreflang [help]

  <entry>
  ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 2, column 0: Missing atom:link with rel="self" [help]

<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
```

Also, the `blog_baseurl` value needs to have a trailing slash or the validator produces a 3rd error:

```
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 3, column 32: Identifier "https://www.rpatterson.net" is not in canonical form (the canonical form would be "https://www.rpatterson.net/") [help]

  <id>https://www.rpatterson.net</id>
```

I greppd that adding the trailing slash doesn't result in double slashes in the generated site.  So the requirement for a trailing slash should be documented or better yet should be added when the site is built/generated.

### Steps to Reproduce

1. Create an Atom blog
2. Publish where publicly available
3. [Validate an Atom feed](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.rpatterson.net%2Fblog%2Fatom.xml)

### System Details

```
$ ./.venv/bin/python --version
Python 3.8.6
$ ./.venv/bin/pip freeze
ablog==0.10.13
alabaster==0.7.12
Babel==2.9.0
certifi==2020.12.5
chardet==4.0.0
docutils==0.16
feedgen==0.9.0
idna==2.10
imagesize==1.2.0
invoke==1.5.0
Jinja2==2.11.3
lxml==4.6.2
MarkupSafe==1.1.1
packaging==20.9
Pygments==2.8.1
pygments-solarized==0.0.3
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
requests==2.25.1
six==1.15.0
snowballstemmer==2.1.0
Sphinx==3.5.2
sphinx-fasvg==0.1.4
sphinx-nervproject-theme==2.0.3
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
urllib3==1.26.4
watchdog==2.0.2
$ uname -a
Linux rpatterson.rpatterson.net 5.8.0-7642-generic #47~1614007149~20.10~82fb226-Ubuntu SMP Tue Feb 23 02
:59:01 UTC  x86_64 x86_64 x86_64 GNU/Linux                                                             
```

**Comment by rpatterson** [comment]
BTW, thanks much for this lovely software.  It's working great for me!

**Comment by nabobalis** [comment]
Will be in the new version v0.10.14 to be out in an hour.

**Comment by rpatterson** [comment]
Oh, my PR #93 doesn't fix W3C validation that I'm aware of, so this should probably be re-opened.  That PR is more about completeness of the feed entry metadata and didn't intentionally address those validation errors.  My needs are met by the existing generated feeds, I just opened this issue to capture what I saw in case it becomes important to fix at some poine.
