### ISSUE TITLE
Index Out of Range with Atom Feeds

### ISSUE THREAD

**Issue by mruge** [sunpy/ablog#96]
### Description

When building with 0.10.14, I receive an index out of bounds error.

### Expected vs Actual behavior

Expected to build HTML directory, instead errors after creating doctree.

```
Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/ablog/post.py", line 744, in generate_atom_feeds
    summary = " ".join(paragraph.astext() for paragraph in post.excerpt[0])
IndexError: list index out of range
The full traceback has been saved in /tmp/sphinx-err-9ltj4i44.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

### Steps to Reproduce

pip install ablog # install latest

Build any sphinx doc...errored on empty doc

### System Details

- SunPy Version:
- Astropy Version:
- Python Version:  Python 3.9.2 (default, Mar 12 2021, 19:04:51)
- OS information: Debian Based Docker Image, sphinxdoc/sphinx-latexpdf

**Comment by nabobalis** [comment]
Thanks for this, I will patch this and get a release out.

**Comment by nabobalis** [comment]
I have tagged a new version: v0.10.15 hopefully it will be out on pypi in about 15 minutes. Can you check that works for you?

**Comment by nabobalis** [comment]
This should now be fixed. Thanks for the report.

**Comment by mruge** [comment]
I can confirm that the new version works on my builds...thanks for the fast turnaround 👍
